# Generated by Django 2.1.15 on 2021-05-23 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer', models.URLField(verbose_name='Referrer')),
                ('date_visited', models.DateTimeField(auto_now_add=True, verbose_name='Date Visited ')),
                ('country', models.CharField(max_length=50, null=True, verbose_name='Country')),
                ('device', models.CharField(max_length=50, null=True, verbose_name='Device')),
                ('browser', models.CharField(max_length=50, null=True, verbose_name='Browser')),
            ],
        ),
        migrations.RemoveField(
            model_name='short',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='short',
            name='visits',
        ),
        migrations.AddField(
            model_name='short',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visits',
            name='short',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Short'),
        ),
    ]
